In [1]:
import numpy as np
import pandas as pd

In [2]:
pwd

'C:\\Users\\LENOVO\\python_For_ml\\Pandas'

In [3]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is 022C-477C

 Directory of C:\Users\LENOVO\python_For_ml\Pandas

04/04/2025  05:25 PM    <DIR>          .
04/02/2025  06:22 PM    <DIR>          ..
04/04/2025  05:20 PM    <DIR>          .ipynb_checkpoints
04/04/2025  01:50 PM            48,282 Combining_DataFrames.ipynb
04/02/2025  09:53 PM            69,017 Conditional Filtering.ipynb
04/02/2025  09:33 PM           129,762 DataFrames.ipynb
04/04/2025  05:25 PM             2,564 Data-Input-Output.ipynb
04/02/2025  07:26 PM                51 example.csv
04/02/2025  07:26 PM             5,022 example.xlsx
04/03/2025  01:49 PM            96,211 Group_By.ipynb
04/02/2025  07:26 PM        25,112,317 hotel_booking_data.csv
04/03/2025  12:48 PM            53,059 Missing_Data.ipynb
04/02/2025  07:26 PM               177 movie_scores.csv
04/02/2025  07:26 PM            17,727 mpg.csv
04/02/2025  07:26 PM             5,022 my_excel_file.xlsx
04/02/2025  07:26 PM                51 new_file.csv
04/02/2025  07:26 PM             5,021 new_workbook.xlsx
04/04/2025  04:22 PM                40 newfile.csv
04/02/2025  07:26 PM            52,132 reshaping_pivot.png
04/02/2025  07:26 PM             5,459 RetailSales_BeerWineLiquor.csv
04/02/2025  07:26 PM             1,320 Sales_Funnel_CRM.csv
04/02/2025  07:26 PM             1,330 sample_table.html
04/02/2025  07:27 PM             8,768 Series.ipynb
04/02/2025  07:26 PM               555 simple.html
04/04/2025  02:32 PM            11,414 Text_Methods.ipynb
04/04/2025  04:03 PM            18,725 TimeMethodsForDateAndTime.ipynb
04/02/2025  07:26 PM            18,752 tips.csv
04/03/2025  12:01 PM           145,831 UseFul_Methods.ipynb
              25 File(s)     25,808,609 bytes
               3 Dir(s)  124,562,239,488 bytes free

In [4]:
import os

In [5]:
os.getcwd()

'C:\\Users\\LENOVO\\python_For_ml\\Pandas'

In [6]:
df = pd.read_csv('example.csv',index_col=0) #header = None

In [7]:
df

     b   c   d
a
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [8]:
df.to_csv('newfile.csv',index = False)

In [9]:
new = pd.read_csv('new_file.csv')

In [10]:
new

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

# FROM HTML TABLES

In [11]:
url = "https://en.wikipedia.org/wiki/World_population"

In [12]:
tables = pd.read_html(url)

In [13]:
len(tables)

27

In [50]:
tables[4]

,#,Most populous countries,2000,2015,2030[A],"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org."
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_2,Unnamed: 2_level_2,Unnamed: 3_level_2,Unnamed: 4_level_2,Unnamed: 5_level_2
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_3,Unnamed: 2_level_3,Unnamed: 3_level_3,Unnamed: 4_level_3,Unnamed: 5_level_3
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_4,Unnamed: 2_level_4,Unnamed: 3_level_4,Unnamed: 4_level_4,Unnamed: 5_level_4
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_5,Unnamed: 2_level_5,Unnamed: 3_level_5,Unnamed: 4_level_5,Unnamed: 5_level_5
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_6,Unnamed: 2_level_6,Unnamed: 3_level_6,Unnamed: 4_level_6,Unnamed: 5_level_6
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_7,Unnamed: 2_level_7,Unnamed: 3_level_7,Unnamed: 4_level_7,Unnamed: 5_level_7
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_8,Unnamed: 2_level_8,Unnamed: 3_level_8,Unnamed: 4_level_8,Unnamed: 5_level_8
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_9,Unnamed: 2_level_9,Unnamed: 3_level_9,Unnamed: 4_level_9,Unnamed: 5_level_9
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_10,Unnamed: 2_level_10,Unnamed: 3_level_10,Unnamed: 4_level_10,Unnamed: 5_level_10
,"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org.",Unnamed: 1_level_11,Unnamed: 2_level_11,Unnamed: 3_level_11,Unnamed: 4_level_11,Unnamed: 5_level_11
0,NaN,Graphs are unavailable due to technical issues...,NaN,NaN,NaN,NaN
1,1,China[B],1270,1376,1416,NaN
2,2,India,1053,1311,1528,NaN
3,3,United States,283,322,356,NaN
4,4,Indonesia,212,258,295,NaN
5,5,Pakistan,136,208,245,NaN
6,6,Brazil,176,206,228,NaN
7,7,Nigeria,123,182,263,NaN
8,8,Bangladesh,131,161,186,NaN
9,9,Russia,146,146,149,NaN
10,10,Mexico,103,127,148,NaN
11,NaN,World total,6127,7349,8501,NaN
12,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...

In [94]:
world_topten=tables[4]

In [97]:
world_topten=world_topten.drop('#',axis = 1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17400\1332395435.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  world_topten=world_topten.drop('#',axis = 1)

In [101]:
world_topten=world_topten.drop('Most populous countries',axis = 1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17400\2449918116.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  world_topten.drop('Most populous countries',axis = 1)

,2000,2015,2030[A],"Graphs are unavailable due to technical issues. Updates on reimplementing the Graph extension, which will be known as the Chart extension, can be found on Phabricator and on MediaWiki.org."
,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1
,Unnamed: 2_level_2,Unnamed: 3_level_2,Unnamed: 4_level_2,Unnamed: 5_level_2
,Unnamed: 2_level_3,Unnamed: 3_level_3,Unnamed: 4_level_3,Unnamed: 5_level_3
,Unnamed: 2_level_4,Unnamed: 3_level_4,Unnamed: 4_level_4,Unnamed: 5_level_4
,Unnamed: 2_level_5,Unnamed: 3_level_5,Unnamed: 4_level_5,Unnamed: 5_level_5
,Unnamed: 2_level_6,Unnamed: 3_level_6,Unnamed: 4_level_6,Unnamed: 5_level_6
,Unnamed: 2_level_7,Unnamed: 3_level_7,Unnamed: 4_level_7,Unnamed: 5_level_7
,Unnamed: 2_level_8,Unnamed: 3_level_8,Unnamed: 4_level_8,Unnamed: 5_level_8
,Unnamed: 2_level_9,Unnamed: 3_level_9,Unnamed: 4_level_9,Unnamed: 5_level_9
,Unnamed: 2_level_10,Unnamed: 3_level_10,Unnamed: 4_level_10,Unnamed: 5_level_10
,Unnamed: 2_level_11,Unnamed: 3_level_11,Unnamed: 4_level_11,Unnamed: 5_level_11
0,NaN,NaN,NaN,NaN
1,1270,1376,1416,NaN
2,1053,1311,1528,NaN
3,283,322,356,NaN
4,212,258,295,NaN
5,136,208,245,NaN
6,176,206,228,NaN
7,123,182,263,NaN
8,131,161,186,NaN
9,146,146,149,NaN
10,103,127,148,NaN
11,6127,7349,8501,NaN
12,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...,Notes: ^ 2030 = Medium variant. ^ China exclud...